CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98 #-fsanitize=address
NAME = bsp
SRC = Fixed.cpp bsp.cpp Point.cpp
OBJ = $(SRC:.cpp=.o)

all: $(NAME)

%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re